In [2]:
#pandas library helps to work with data as tables
import pandas as pd
#numpy for using number as matrices
import numpy as np
import tensorflow as tf

In [42]:
#Step 1 - Load data with pandas library
dataframe = pd.read_csv('data.csv')
#remove unwanted features
dataframe = dataframe.drop(['index','price','sq_price'],axis = 1)
#use first 10 rows
dataframe = dataframe[0:10]
dataframe

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0
5  1985.0        4.0
6  1534.0        3.0
7  1427.0        3.0
8  1380.0        3.0
9  1494.0        3.0

In [43]:
#Step 2 - adding labels to dataset
#1 is label for a good buy and 2 for bad buy
dataframe.loc[:, ('y1')] = [1,1,1,0,0,1,0,1,1,1]
dataframe.loc[:, ("y2")] = dataframe["y1"] == 0           # y2 is the negation of y1
dataframe.loc[:, ("y2")] = dataframe["y2"].astype(int)

In [44]:
#Step 3 - Prepare data for tensorflow i.e tensors
#tensor is a genreic term for matrices
#1D tensor, 2D tensor, 3D tensor an so on...

#convert features into input tensors
inputX = dataframe.loc[:, ['area', 'bathrooms']].as_matrix()
inputY = dataframe.loc[:, ["y1", "y2"]].as_matrix()
print(inputX)
print(inputY)

[[  2.10400000e+03   3.00000000e+00]
 [  1.60000000e+03   3.00000000e+00]
 [  2.40000000e+03   3.00000000e+00]
 [  1.41600000e+03   2.00000000e+00]
 [  3.00000000e+03   4.00000000e+00]
 [  1.98500000e+03   4.00000000e+00]
 [  1.53400000e+03   3.00000000e+00]
 [  1.42700000e+03   3.00000000e+00]
 [  1.38000000e+03   3.00000000e+00]
 [  1.49400000e+03   3.00000000e+00]]
[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]


In [45]:
#Step 4 - Define hyperparameters
learning_rate = 0.000001
epochs = 2000
display_step = 5
n_samples = inputY.size

In [46]:
x = tf.placeholder(tf.float32, [None, 2])   # Okay TensorFlow, we'll feed you an array of examples. Each example will
                                            # be an array of two float values (area, and number of bathrooms).
                                            # "None" means we can feed you any number of examples
                                            # Notice we haven't fed it the values yet
            
W = tf.Variable(tf.zeros([2, 2]))           # Maintain a 2 x 2 float matrix for the weights that we'll keep updating 
                                            # through the training process (make them all zero to begin with)
    
b = tf.Variable(tf.zeros([2]))              # Also maintain two bias values

y_values = tf.add(tf.matmul(x, W), b)       # The first step in calculating the prediction would be to multiply
                                            # the inputs matrix by the weights matrix then add the biases
    
y = tf.nn.softmax(y_values)                 # Then we use softmax as an "activation function" that translates the
                                            # numbers outputted by the previous layer into probability form
    
y_ = tf.placeholder(tf.float32, [None,2])   # For training purposes, we'll also feed you a matrix of labels

In [47]:
#Step 6 - Perform Training
#Create our cost function which is a mean squared error function
#Reduced sum computes sum of elements across dimensions of a tensor
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples)
# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [48]:
#Step 7 - Initialize all variables and tensorflow session
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [49]:
#Step 8 - Training Loop
for i in range(epochs):  
    sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) # Take a gradient descent step using our inputs and labels

    # That's all! The rest of the cell just outputs debug messages. 
    # Display logs per epoch step
    if (i) % display_step == 0:
        cc = sess.run(cost, feed_dict={x: inputX, y_:inputY})
        print("Training step:", '%04d' % (i), "cost=", "{:.9f}".format(cc)) #, \"W=", sess.run(W), "b=", sess.run(b)

print("Optimization Finished!")
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')

Training step: 0000 cost= 0.114958666
Training step: 0005 cost= 0.109683201
Training step: 0010 cost= 0.109547928
Training step: 0015 cost= 0.109540485
Training step: 0020 cost= 0.109540008
Training step: 0025 cost= 0.109539971
Training step: 0030 cost= 0.109539986
Training step: 0035 cost= 0.109539963
Training step: 0040 cost= 0.109539963
Training step: 0045 cost= 0.109539948
Training step: 0050 cost= 0.109539941
Training step: 0055 cost= 0.109539941
Training step: 0060 cost= 0.109539926
Training step: 0065 cost= 0.109539911
Training step: 0070 cost= 0.109539911
Training step: 0075 cost= 0.109539904
Training step: 0080 cost= 0.109539889
Training step: 0085 cost= 0.109539889
Training step: 0090 cost= 0.109539889
Training step: 0095 cost= 0.109539881
Training step: 0100 cost= 0.109539866
Training step: 0105 cost= 0.109539866
Training step: 0110 cost= 0.109539866
Training step: 0115 cost= 0.109539852
Training step: 0120 cost= 0.109539844
Training step: 0125 cost= 0.109539844
Training ste

Training step: 1230 cost= 0.109538339
Training step: 1235 cost= 0.109538317
Training step: 1240 cost= 0.109538317
Training step: 1245 cost= 0.109538317
Training step: 1250 cost= 0.109538317
Training step: 1255 cost= 0.109538294
Training step: 1260 cost= 0.109538294
Training step: 1265 cost= 0.109538279
Training step: 1270 cost= 0.109538272
Training step: 1275 cost= 0.109538272
Training step: 1280 cost= 0.109538242
Training step: 1285 cost= 0.109538242
Training step: 1290 cost= 0.109538242
Training step: 1295 cost= 0.109538242
Training step: 1300 cost= 0.109538242
Training step: 1305 cost= 0.109538235
Training step: 1310 cost= 0.109538220
Training step: 1315 cost= 0.109538220
Training step: 1320 cost= 0.109538212
Training step: 1325 cost= 0.109538198
Training step: 1330 cost= 0.109538198
Training step: 1335 cost= 0.109538175
Training step: 1340 cost= 0.109538183
Training step: 1345 cost= 0.109538175
Training step: 1350 cost= 0.109538175
Training step: 1355 cost= 0.109538153
Training ste

In [50]:
sess.run(y,feed_dict = {x:inputX})

array([[ 0.71125227,  0.28874776],
       [ 0.66498977,  0.33501023],
       [ 0.73657656,  0.26342347],
       [ 0.64718795,  0.35281211],
       [ 0.78335613,  0.21664388],
       [ 0.7006948 ,  0.29930523],
       [ 0.65866327,  0.34133673],
       [ 0.64828628,  0.35171375],
       [ 0.64368278,  0.35631716],
       [ 0.65480119,  0.34519887]], dtype=float32)